os: Visual Studio 2017

version: 1.0.0-{build}

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - dotnet restore

test_script:
  - dotnet test "eWAY.Rapid.Tests\eWAY.Rapid.Tests.csproj" --configuration Release

build_script:
  - dotnet pack "eWAY.Rapid" --configuration Release --output "bin" --version-suffix {build}

artifacts:
  - path: eWAY.Rapid\bin\eWAY.Rapid.*.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: +AIEY0E9rURDXqzW7YM/RoRXDhOxdTZQ4XyUxNCKR6zaHvj7ha/uZHnhqofdaUu3
  skip_symbols: false
  on:
   appveyor_repo_tag: true