os: Visual Studio 2019

version: 1.0.{build}

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - dotnet restore

test_script:
  - dotnet test "eWAY.Rapid.Tests\eWAY.Rapid.Tests.csproj" --configuration Release

build_script:
  - ps: dotnet pack "eWAY.Rapid" --configuration Release --output "bin" /p:PackageVersion=$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))

artifacts:
  - path: bin\*.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: 8wXbZI9X4oEOCRMO0nW7ayJvSb2EiaGhaF2Zpxs9iizLgK96HnDyPXp1632Da8vo
  skip_symbols: false
  on:
   appveyor_repo_tag: true